services:
  api-node:
    container_name: backend
    build: .
    image: api-node:1.0
    ports:
      - "3000:3000"
    networks:
      - api-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: banco_teste
      MYSQL_USER: bertolo
      MYSQL_PASSWORD: bertolo123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local